<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="672" started-at="2020-11-19T11:06:30Z" finished-at="2020-11-19T11:06:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="672" started-at="2020-11-19T11:06:30Z" finished-at="2020-11-19T11:06:30Z">
      <class name="com.qa.test.OrganizeTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.test.OrganizeTest@639c2c1d]" name="setUp" is-config="true" duration-ms="395" started-at="2020-11-19T19:06:30Z" finished-at="2020-11-19T19:06:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="addUser(java.lang.String)[pri:1, instance:com.qa.test.OrganizeTest@639c2c1d]" name="addUser" duration-ms="14" started-at="2020-11-19T19:06:30Z" description="添加用户" data-provider="data" finished-at="2020-11-19T19:06:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"roleList":[{"groupId":0,"groupName":"默认小组","privilege":2}],"login_name":"testql4","passwd":"12345678a","session_time":5,"is_usable":true,"is_manager":false,"name":"","email":"","position":"","department":"sww22","company_name":""}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addUser -->
        <test-method status="PASS" signature="addUser(java.lang.String)[pri:1, instance:com.qa.test.OrganizeTest@639c2c1d]" name="addUser" duration-ms="8" started-at="2020-11-19T19:06:30Z" description="添加用户" data-provider="data" finished-at="2020-11-19T19:06:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"roleList":[{"groupId":0,"groupName":"默认小组","privilege":2}],"login_name":"testql4","passwd":"12345678a","session_time":5,"is_usable":true,"is_manager":false,"name":"","email":"","position":"","department":"sww22","company_name":""}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addUser -->
        <test-method status="FAIL" signature="editUser()[pri:3, instance:com.qa.test.OrganizeTest@639c2c1d]" name="editUser" duration-ms="103" started-at="2020-11-19T19:06:30Z" description="编辑用户" finished-at="2020-11-19T19:06:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.qa.test.OrganizeTest.getUser(OrganizeTest.java:71)
	at com.qa.test.OrganizeTest.editUser(OrganizeTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editUser -->
        <test-method status="FAIL" signature="delteUser()[pri:4, instance:com.qa.test.OrganizeTest@639c2c1d]" name="delteUser" duration-ms="54" started-at="2020-11-19T19:06:30Z" description="删除用户" finished-at="2020-11-19T19:06:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.qa.test.OrganizeTest.getUser(OrganizeTest.java:71)
	at com.qa.test.OrganizeTest.delteUser(OrganizeTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delteUser -->
        <test-method status="PASS" signature="addGroup()[pri:5, instance:com.qa.test.OrganizeTest@639c2c1d]" name="addGroup" duration-ms="37" started-at="2020-11-19T19:06:30Z" description="添加小组" finished-at="2020-11-19T19:06:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addGroup -->
      </class> <!-- com.qa.test.OrganizeTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
